#!/usr/bin/python2
import sys
import timeit

files=sys.argv[1:3] #Taking source files
sr_file=files[0] #Extracting source
#extracting the source file name      
file_name=sr_file.split('/')

ds_file=files[1] #Extracting destination
print ds_file[-1]
#checking if destination file is given or not
if '/' == ds_file[-1]:
	ds_file=ds_file+file_name[-1]

f1=open(sr_file,'r') #opening the source in read mode
s_data=f1.read() 
f1.close #closing source file
f2=open(ds_file,'w') #opening the destination file in write mode
f2.write(s_data) #copying data from source to destination
f2.close()

#measuring the time taken by pycp in seconds
s=timeit.timeit(""" 
files=sys.argv[1:3] #Taking source files
sr_file=files[0] #Extracting source
#extracting the source file name      
file_name=sr_file.split('/')

ds_file=files[1] #Extracting destination
print ds_file[-1]
#checking if destination file is given or not
if '/' == ds_file[-1]:
        ds_file=ds_file+file_name[-1]



f1=open(sr_file,'r') #opening the source in read mode
s_data=f1.read() 
f1.close #closing source file
f2=open(ds_file,'w') #opening the destination file in write mode
f2.write(s_data) #copying data from source to destination
f2.close()
""",number=1)
print s,"is the time required to copy file using pycp 1 time"


#measuring the time taken by cp command in seconds
h=timeit.timeit("""
import commands
commands.getoutput('cp /root/Desktop/lo.txt /root/a.txt')""",number=1)
print h,"is the time required for cp cmd"

